### ISSUE TITLE
Refactor unit tests to reduce test setup duplication

### ISSUE THREAD

**Issue by UberMouse** [MindscapeHQ/raygun4ruby#102]
The current unit tests are fairly lengthy, primarily because a lot of them have similar setup that could be shared between them. This could be improved either by potentially moving to a BDD style test suite and making use of before hooks or creating setup methods to create the data.

**Comment by nikz** [comment]
Not sure moving test suites is beneficial, but there's definitely some duplication in the `env` hashes that could be cleaned up.

**Comment by UberMouse** [comment]
I'm re doing the whitelisting feature that @fundead started on to simplify the process, making it in its own service object so as to not complicate the client class. I'm using the `minitest/spec` tests for that since it's decoupled from the existing unit tests. 

But yes, it's probably not beneficial to move the existing unit tests to that style so when I get time I'll just refactor them to have some setup methods to generate the stacktrace information/env hashes/anything else that stands out as similar.
