### ISSUE TITLE
Raygun::Breadcrumbs::Store error on test enviroment

### ISSUE THREAD

**Issue by ottony** [MindscapeHQ/raygun4ruby#124]
When running specs, this exception was raised when record_breadcrumb is called.

```
NoMethodError:
 undefined method `<<' for nil:NilClass

# raygun4ruby-2.4.0/lib/raygun/breadcrumbs/store.rb:43:in `record'
# raygun4ruby-2.4.0/lib/raygun.rb:81:in `record_breadcrumb'
```

I solved that by explicitly calling `Raygun::Breadcrumbs::Store.initialize` on my test setup, but maybe is a good idea do it automatically or make it clear in Readme.

**Comment by UberMouse** [comment]
Yep, the behaviour around this could definitely be improved. I should have some time to do some work on Raygun4Ruby late this week/early next week so I'll do some improvements around this area then.

**Comment by ottony** [comment]
Nice!
I realized that is the same thing with the Sidekiq.

**Comment by ottony** [comment]
Nice!
I realized that the same thing occurs on Sidekiq.
