### ISSUE TITLE
Javascript Error Tracking Helper Method?

### ISSUE THREAD

**Issue by MikeRogers0** [MindscapeHQ/raygun4ruby#132]
Is there any interest in adding a helper methods for injecting the [JavaScript](https://raygun.com/docs/languages/javascript) error tracking code into HTML views for Rails?

If there is I'd happily work on a PR :)

**Comment by UberMouse** [comment]
Sure, I'd be happy to have something like this in the library. Would just need an extra configuration option for the javascript API key.

If you get a PR together I'll take a look at it.

**Comment by MikeRogers0** [comment]
> Would just need an extra configuration option for the javascript API key.

@UberMouse I was going to use `Raygun.configuration.api_key` to output the API key, do accounts have a different JavaScript API key from the one used for Ruby exceptions?

**Comment by UberMouse** [comment]
Yes, it's considered best practice to separate your frontend errors from your backend errors as they happen in different languages/contexts and could potentially be managed by different teams.

**Comment by MikeRogers0** [comment]
@UberMouse Ah that makes sense, thank you for clarifying that :)

**Comment by MikeRogers0** [comment]
I've semi started on this https://github.com/MikeRogers0/raygun4ruby/tree/feature/js-error-tracking 

How do you feel about using me implementing a middleware for injecting the script tag into people html documents (A bit like the way [New Relic is doing it](https://github.com/newrelic/rpm/blob/17734c85a9251ede14fbee517f0d264d99116c7e/lib/new_relic/rack/browser_monitoring.rb))?

**Comment by UberMouse** [comment]
That approach seems like it would make sense to me

**Comment by MikeRogers0** [comment]
HI hi! I got the middleware written (Sorry it took a while, I started a new job this month which is taking a lot of my focus). 

I need to write some decent integrations test for it, I noticed you have both `test`/`spec` - Do you have a preferences in how I do it?
I'm thinking of copying the devise approach of having a [rails_app](https://github.com/plataformatec/devise/tree/master/test/rails_app), where I just fire a http request at it and verify adding the `js_api_key` injects the JS. Then some unit tests to make sure edge cases are covered.

I also was thinking about contextual configuration (So adding user/environment info to the JS payload) as part of this, but I'll leave that until later :)

**Comment by UberMouse** [comment]
Hey, preference is spec. The new tests have been written with `spec` when I took over maintainership, the existing ones were `test`. That approach to the integration test sounds fine.

**Comment by MikeRogers0** [comment]
Awesome (Also, thank you for the speedy reply!)! 
I like Rspec more then Minitest, so that's perfect :)

**Comment by UberMouse** [comment]
Merged & deployed as part of #134, #138 and v3.1.0

**Comment by MikeRogers0** [comment]
Woo thank you @UberMouse :D
