### ISSUE TITLE
Cannot find code in this repo that corresponds to version 3.0.0 on rubygems

### ISSUE THREAD

**Issue by eoinkelly** [MindscapeHQ/raygun4ruby#137]
Rubygems has version 3.0.0 of this gem https://rubygems.org/gems/raygun4ruby/versions/3.0.0 but I can't find any reference to that release in this repo. The latest tag I can find is `v2.7.0` https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/version.rb shows `"2.7.1"` as the latest version. It's a bit unnerving to not be able to read over the code of a major version bump). I'm assuming somebody forgot a pre-xmas git push 😄

**Comment by UberMouse** [comment]
Hey Eoin,

Sorry about that, I did forget to push to Github. I've pushed it up now, the version bump is very minor I'm just sticking to semver and it is technically a breaking change :)
