### ISSUE TITLE
Filter Header and Cookie values

### ISSUE THREAD

**Issue by blischalk** [MindscapeHQ/raygun4ruby#150]
Is it possible to filter cookie and header values that would be sent to Raygun? This seems to be available in the Raygun4Java version at: https://github.com/MindscapeHQ/raygun4java. I have looked into using `config.filter_parameters` with a proc but it does not seem that the entire request hash is passed.

Thank you!

**Comment by UberMouse** [comment]
Hi @blischalk,

You can filter the header and cookie values in Raygun4Ruby, just not as cleanly as with Raygun4Java. You can make use of the [filtering by whitelist](https://github.com/MindscapeHQ/raygun4ruby#filtering-the-payload-by-whitelist) functionality with a proc to get passed the entire set of error details that will be sent to Raygun. You are then free to mutate and return the passed error details object as you see fit to strip out any header or cookie values you need to remove.

It's not the best approach and I can look at providing an improved method of doing this in the future, but that won't be soon.

**Comment by blischalk** [comment]
Hello @UberMouse,

When attempting to use the whitelist approach that you mention, I receive the following error:

```
undefined method `whitelist_payload_keys' for #<Raygun::Configuration:0x0055b3222afc30> (NoMethodError)
  /srv/app/local/config/initializers/raygun.rb:14:in `block in <top (required)>'
  /home/someuser/ruby/2.1.0/gems/raygun4ruby-3.2.1/lib/raygun.rb:38:in `setup'
```

This is raised when using the configuration out of the readme that looks like the following:

```
  config.filter_payload_with_whitelist = true
  config.whitelist_payload_keys do |payload|
    # Return the payload mutated into your desired form
    payload
  end
```

Any idea what might cause this?

I did a github search through the gem codebase and the only reference to `whitelist_payload_keys` seems to be in the README.md.

**Comment by UberMouse** [comment]
Sorry about that, the README was incorrect. You should still be using `whitelist_payload_shape` like the example above it, there is no config option called `whitelist_payload_keys`

**Comment by blischalk** [comment]
After looking into `whitelist_payload_keys` it seems that using this essentially leaves all filtering to the user. Is this accurate? If so, to replicate the filtering that this gem provides when using `config.filter_parameters` and then additionally filter out a cookie, it seems like someone would need to:

- Perform recursive filtering of a list of blacklisted keys within payload[:request][:form]
- Perform recursive filtering of a list of blacklisted keys within payload[:userCustomData]
- Perform recursive filtering of a list of blacklisted keys within payload[:rawData]
- Perform string substitution of the "Cookies" field doing something similar to: `payload[:request][:headers]["Cookie"].gsub(/;?\s?_cookie_name_here=\w+;?/, '')`

Is there anything else that might be getting filtered within the payload that I might have missed? Does this accurately capture what you were suggesting?

**Comment by UberMouse** [comment]
I've had a look through the code and I actually think the README comment about enabling whitelisting turning off blacklisting is incorrect. I just a did a test locally and using `whitelist_payload_shape` with a proc allowed me to mutate a single field of the `error_details` object while still having the `filter_parmeters` applied to the payload.

**Comment by blischalk** [comment]
Thank you for your help @UberMouse! That is exactly what I was looking for.
