### ISSUE TITLE
Support Tags for Sidekiq?

### ISSUE THREAD

**Issue by gchan** [MindscapeHQ/raygun4ruby#159]
Hi there,

We have been organising our exceptions with tagging as suggested here: https://raygun.com/blog/reduce-error-noise/

However the current implementation of this gem's Sidekiq integration doesn't permit configuration of tags. Are you open to supporting custom tags or hard-coding a tag `sidekiq` into the `custom_data` Hash? 

Relevant code:
https://github.com/MindscapeHQ/raygun4ruby/blob/801f195622bc068b79b478613412e68a11a39fa6/lib/raygun/sidekiq.rb#L23-L27

Thanks

**Comment by gchan** [comment]
@samuel-holt @Deacon-McIntyre thoughts on this?

**Comment by Deacon-McIntyre** [comment]
Hi @gchan, thanks for raising this. A `sidekiq` tag sounds sensible to us, we'll look at making this change soon.

**Comment by Deacon-McIntyre** [comment]
Released as version 3.2.4 of the gem @gchan

**Comment by gchan** [comment]
Thank you @Deacon-McIntyre !
