### ISSUE TITLE
Support Ruby 3 ?

### ISSUE THREAD

**Issue by cprodhomme** [MindscapeHQ/raygun4ruby#167]
Hello,

we have install this gem on our project which uses ruby ​​3.0.1 but we have zero errors on our interface. Maybe the gem doesn't support this version?

I saw that the `.travis.yml` does not include ruby ​​3.0.1 for the test

is this possible to add some test on this ruby version ?

Thanks !

**Comment by nikz** [comment]
Hiya - apologies for the slow reply. I believe the gem supports Ruby 3.0 - at least I've been using it for a 3.0 app for a while now! 

Work is in progress to update the testing versions to reflect that.
