### ISSUE TITLE
Update Affected User tracking

### ISSUE THREAD

**Issue by jamiepenney** [MindscapeHQ/raygun4ruby#32]
We are adding a bit more information to the affected user tracking feature in Raygun - could you add support for it as well?

Here it is in the Raygun .Net provider:
https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net/Messages/RaygunIdentifierMessage.cs
And the documentation for it is here:
https://github.com/MindscapeHQ/raygun4net#affected-user-tracking

Cheers,
Jamie

**Comment by UberMouse** [comment]
Resolved by #34
