### ISSUE TITLE
Params aren't supported for non-form requests?

### ISSUE THREAD

**Issue by eprothro** [MindscapeHQ/raygun4ruby#45]
I'm trying out raygun for a REST JSON API based platform (web, iOS, and Android clients).

My API's app code handles all errors, reporting to an error service with the following client:

``` ruby
# note: Sidekiq reporting works by requiring 'raygun/sidekiq'
#       in config/initializers/raygun.rb
class RaygunReporter < ErrorReporterClient
  self.instance_eval do
    def configured?
      # creating a client raises if it doesn't have an API key
      Raygun::Client.new rescue false
    end
  end

  def report(exception)
    opts = request.try(:env) || {}
    opts[:custom_data] = context_hash if context_hash.present?
    # Raygun.track_exception(exception, opts={})
    #
    #   Request info is extracted from the 2nd arg, expecting
    #   that it be a superset of ::Rack Environment hash.
    #   If a `:custom_data` key is present, that is extracted
    #   and reported as custom context
    Raygun.track_exception(exception, opts)
  end
end
```

Upon testing, I noticed that no "Params Values" ever make it through to the error reports.

After further looking at https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb, it appears that we could only expect to get parameter information for requests that have form data media types (https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L101). 

Is there a way to report parameters in non-form requests, that I'm missing? Is it then intent of the library that there shouldn't be? More info will help me know how to move forward (patch, fork, cry, etc).

Thanks!

**Comment by UberMouse** [comment]
This looks to have been resolved by #53
