### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by fourseven** [MindscapeHQ/raygun4ruby#67]
Hello, I've finally had a chance to look into affected user tracking, which hasn't been working for us (we're on 1.1.5 of the gem) - I see that you've fixed it in master. 

Could you please release (soon) so we don't have to have a github: dependancy in our Gemfile?

**Comment by nikz** [comment]
:sparkles: [Your wish is my command](https://github.com/MindscapeHQ/raygun4ruby/releases/tag/1.1.6) :sparkles: 

Enjoy! :smile:
