### ISSUE TITLE
Allow a default array of tags to be set in configuration

### ISSUE THREAD

**Issue by eoinkelly** [MindscapeHQ/raygun4ruby#72]
We have a project which is deploying to a mix of AWS and Heroku environments. Unfortunately Heroku forces you to use the `production` env and we already have a "real" `production` env which is managed by a separate ops team so changing the name isn't feasible.

I am working around this by adding a flag to `customData` to indicate when exceptions come from the Heroku env but I can't seem to find a way to filter by customData on the Raygun webapp.

I would like to be able to set a default array of tags in the block passed to `Raygun.setup` so that I can be sure that _every_ exception passed to raygun will get the appropriate tag i.e. I would like to be able to do

```
Raygun.setup do |config|
  config.api_key = Rails.application.secrets.raygun_api_key
  config.filter_parameters = Rails.application.config.filter_parameters
  config.tags = [ 'from_heroku' ]
end
```

Currently I can add a custom tag via `.track_exception` but this does not work for Exceptions that bubble all the way up.

**Comment by nikz** [comment]
Hey man - sounds like a good addition. If you wanna throw that together that'd be choice, otherwise I'll hope to get around to it sometime in the next few weeks.

**Comment by eoinkelly** [comment]
Sweet, I'll try to have a crack at it this week (time depending).

**Comment by nikz** [comment]
Let me know where you get to, and the @mindscapeHQ folks are crazy responsive if you need API-help or anything.
