### ISSUE TITLE
config.relative_url_root

### ISSUE THREAD

**Issue by dennisvandehoef** [MindscapeHQ/raygun4ruby#81]
Hey,

In our app we set an relative_url_root like this `config.relative_url_root = '/cms'` but raygun seems to ignore it.
(in the raygun web gui) erros on: /cms/pages in raygun get an link to /pages.

How can we explain raigun4ruby that we have set relative_url_root and/or what it's value is.

Manny thanks,
Dennis

**Comment by nikz** [comment]
Hi Dennis,

Raygun4Ruby is using `env["PATH_INFO"]` (https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L93).

I'm not sure if there is an entry in your `env` hash that includes the relative_url_root?

Cheers,

Nik

**Comment by dennisvandehoef** [comment]
Hi Nik,

I have testet it and env["PATH_INFO"] contains "/pages".
But i also found: env["SCRIPT_NAME"] wich contains the missing "/cms"

And then there is also the env["REQUEST_URI"] wich contains http://www.foobar.de.dev/cms/pages?action=index&controller=pages&locale=en-GB&locale=de"
From where I stand env["SERVER_NAME"] is just `env["SCRIPT_NAME"] + env["PATH_INFO"] + '?' + env["QUERY_STRING"]`

Cheers,
Dennis

**Comment by dennisvandehoef** [comment]
hmmm I just checked raygun and see that /cms is in the error.
Strange, since the env variable does not gives a value with /cms, but I am happy.

(did not change a thing).

Thanks for you time and Happy Hollidays,
Dennis

**Comment by nikz** [comment]
:+1:
