### ISSUE TITLE
Affected user doesn't show when I manually call track_exception

### ISSUE THREAD

**Issue by stevehanson** [MindscapeHQ/raygun4ruby#82]
I see affected users in Raygun for exceptions that I don't catch and are automatically reported, but when I call `Raygun.track_exception`, the affected user doesn't get set. Is there something I need to do for this to happen?

**Comment by stevehanson** [comment]
OK, I figured out how to do this after digging through the code. I just need to pass the following when I call `track_exception`:

```
{ user: { identifier: "user@example.com" } }
```

So, here's an example of error tracking with affected user for anyone else reading this:

```
Raygun.track_error(error, {
  user: {
    identifier: "user@example.com"
  },
  custom_data: {}
})
```

**Comment by stevehanson** [comment]
This can be closed now I think. Would it be OK if I open a PR with a documentation update to clarify this?

**Comment by nikz** [comment]
@stevehanson yes, a PR to that effect will be enthusiastically merged :)
