### ISSUE TITLE
custom grouping

### ISSUE THREAD

**Issue by murtyk** [MindscapeHQ/raygun4ruby#83]
[Api documentation](https://raygun.com/docs/integrations/api) says we can pass groupingKey for custom grouping. How do we do that using this gem?

**Comment by nikz** [comment]
@murtyk this isn't supported just yet I'm afraid, although you could just [add it to the hash here](https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L144). PRs enthusiastically accepted!

**Comment by murtyk** [comment]
@nikz I am ready with the change but when I try to publish but authentication is failing. How do I push my changes and create the pr?

**Comment by UberMouse** [comment]
Seems to be fixed by #85 so I'm closing
