### ISSUE TITLE
Is it possible to relax the version requirement for httparty?

### ISSUE THREAD

**Issue by steveh** [MindscapeHQ/raygun4ruby#94]
Having httparty locked to 0.13.7 means I can't run this simultaneously with something that requires 0.14.0.

Thanks!

**Comment by artemave** [comment]
This appears to be fixed https://github.com/MindscapeHQ/raygun4ruby/commit/031d0ff6a5dd8afff31a0d1af45fc2bbf14bd92d

**Comment by anthonator** [comment]
Would it be possible to release this? We currently can't upgrade to Ruby 2.4.0 due to this.

**Comment by nikz** [comment]
Sure, I've pushed 1.1.12 for you now :)
